server:
  port: 8070

spring:
  application:
    name: gmall-user-service

  datasource:
    url: jdbc:mysql://localhost:3306/gmall_study
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

# dubbo 配置
  dubbo:
    application:
      name: user-service  # 注册的服务名称

    protocol:
      name: dubbo # dubbo通信协议

    registry:
      address: 192.168.138.128:2181 # zookeeper注册中心地址
      protocol: zookeeper # 注册中心协议

    base-package: com.atguigu.gmall # dubbo扫描路径 这里配置错误 dubbo扫描不到服务

logging:
  level:
    com.atguigu.gmall: debug

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
