server:
  port: 8082

spring:
  application:
    name: gmall-item-web

# dubbo 配置
  dubbo:
    application:
      name: item-web  # 注册的服务名称

    protocol:
      name: dubbo # dubbo通信协议

    registry:
      address: 192.168.138.128:2181 # zookeeper注册中心地址
      protocol: zookeeper # 注册中心协议

    base-package: com.atguigu.gmall # dubbo扫描路径 这里配置错误 dubbo扫描不到服务

    consumer:
      check: false
      timeout: 6000

logging:
  level:
    com.atguigu.gmall: debug


# 线程池配置
gmall:
  pool:
    main:
      corePoolSize: 5
      maximumPoolSize: 16
      workQueueCapacity: 100

    general:
      corePoolSize: 2
      maximumPoolSize: 8
      workQueueCapacity: 20

